### ISSUE TITLE
Lock models on a per-language basis at loading time

### ISSUE THREAD

**Issue by Julm** [ixa-ehu/ixa-pipe-nerc#14]
Hi again Rodrigo :)

Thank you for making ixa-pipe-* thread-safe, that is so useful!

I'd like to propose to go a bit further and not locking the whole map at model loading time but locking model per model in order to let the users load two different models at the same time.

Here is a patch proposal. You already know it, but note that a similar patch would apply to ixa-pipe-pos.

Does it make sense? What do you think?

Kind regards,
Julien
[per-lang_model_locking.patch.zip](https://github.com/ixa-ehu/ixa-pipe-nerc/files/1080905/per-lang_model_locking.patch.zip)

**Comment by ragerri** [comment]
Hello,

Could you send a PR via github so I can take a look at it and merge it?

Thanks!

R

**Comment by Julm** [comment]
Hi Rodrigo,

Done! I did submit a pull request. 

Thanks,
Best,
Julien

**Comment by ragerri** [comment]
I know, and thanks a lot.

I will look at it soon and merge it.

Thanks,

R

**Comment by Julm** [comment]
You're very welcome.

No hurry :) 

Thanks!

**Comment by ragerri** [comment]
merged in ixa-pipe-ml
