### ISSUE TITLE
Implementing the model for a new language

### ISSUE THREAD

**Issue by asmundur** [ixa-ehu/ixa-pipe-nerc#17]
Just a quick question, does the project support the functionality of implementing the NER model for a new language? 

I'm interested in experimenting with this model but on Icelandic text, I have a corpus ready for that, so that wouldn't be an issue for me.

**Comment by ragerri** [comment]
Hello,

Yes, if you have annotated data in the CoNLL (2002 or 2003) format all you
have to do is to run the "sequenceTrainer" command. The training
functionality has now moved to

https://github.com/ixa-ehu/ixa-pipe-ml#training

1. You train with ixa-pipe-ml and then
2. You use the model to tag text with ixa-pipe-nerc.

This is the training parameters file:

https://github.com/ixa-ehu/ixa-pipe-ml/blob/master/sequenceTrainer.properties

For better performance, it is convenient to use the clustering features, as
shown here:

https://doi.org/10.1016/j.artint.2016.05.003

https://arxiv.org/abs/1701.09123

Cheers,

R
